global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "ono-backend-dev"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["app-dev:8080"]

  - job_name: "rabbitmq-exporter-dev"
    static_configs:
      - targets: ["rabbitmq-exporter-dev:9419"]

  - job_name: "redis-exporter-dev"
    static_configs:
      - targets: ["redis-exporter-dev:9121"]

  - job_name: "mysqld-exporter-dev"
    static_configs:
      - targets: ["mysqld-exporter-dev:9104"]

  - job_name: "cadvisor-dev"
    static_configs:
      - targets: ["cadvisor-dev:8080"]
