global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "ono-backend-prod-blue"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["app-prod-blue:8080"]

  - job_name: "ono-backend-prod-green"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["app-prod-green:8080"]
